---
title: "Vizualization"
author: "Durjoy Sarker"
format:
  pdf:
    toc: true
    toc-depth: 2
---

## Line graph
### Basics
```{r}
v <- c(13,12,45,34,56,67,89,78,56,78,90) 
#this is just create point
plot(v,type = "p")

#this is just create line 
plot(v,type = "l")

#this is create both line and point
plot(v,type = "o") 
```

### With the headline
```{r}
days = c(10,20,30,40,50,60,70,80,90) 
income <- c(1000,3000,4500,6700,7800,8900,9900,11000,12000) 
plot(days,income,type = "o",main = "Salary",xlab = "days",ylab = "income", col="green") 
```

### Multiple Graph
```{r}
f <- c(3,5,2,7,4,8,9,4) 
g <- c(4,6,8,6,7,4,7,5) 
j <- c(3,5,6,5,8,9,5,8) 
plot(f, type="o",main="multiple graph",xlab="days",ylab="time",col="blue") 
lines(g, type="o",col="green") 
lines(j, type="o",col="red")
```



## Bar Graph
```{r}
#Create the matrix of the values
values <- matrix(c(2, 9, 3, 11, 9, 4, 8, 7, 3, 12, 5, 2, 8, 10, 11),nrow=3, ncol=5, byrow=TRUE)
#Create the bar chart
barplot(values, main="Total Revenue", name.arg=months, xlab="Month",ylab="Revenue",  col = colors, beside =TRUE)
```

## ggplot
```{r}
data <- data.frame(
  x = c(1, 2, 3, 4, 5), 
  y = c(3, 5, 2, 8, 7) 
)

library(ggplot2)
ggplot(data,aes(x,y))+
  geom_line(color= "blue")+
  geom_point(size=3)+
  labs(title="Practice of ggplot", subtitle="add any subtitle hare",caption="add any caption hare", x="x axis", y="y axis")+
  theme_classic()
```
















